name: Posix

on:
  push:
  pull_request:

env:
  UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1

jobs:
  build:
    strategy:
      matrix:
        config: [ Debug, Release ]
        params: [ { os: ubuntu-latest },
                  { os: macos-latest  } ]
    runs-on: ${{ matrix.params.os }}
    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4
    - name: install
      run:  |
        sudo apt-get update
        sudo apt-get install -y liburing-dev
      if: matrix.params.os == 'ubuntu-latest'
    # Install 7zip just to check that links are still valid
    - name: package install 7zip
      run: ./SC.sh package install 7zip
    - name: Generate Single File Libs (Python)
      run: python3 Support/SingleFileLibs/python/amalgamate_single_file_libs.py
    - name: configure SCTest
      run: ./SC.sh build configure SCTest ${{ matrix.config }}
    - name: configure SCSingleFileLibs
      run: ./SC.sh build configure "SCSingleFileLibs:" ${{ matrix.config }}
    - name: compile SCTest
      run: ./SC.sh build compile SCTest ${{ matrix.config }}
      if: matrix.params.os != 'macos-latest' || matrix.config != 'Release'
    - name: compile SCSingleFileLibs
      run: ./SC.sh build compile "SCSingleFileLibs:" ${{ matrix.config }}
    - name: compile InteropSTL
      run: ./SC.sh build compile InteropSTL ${{ matrix.config }}
    - name: test SCTest
      run: ./SC.sh build run SCTest ${{ matrix.config }} -- --all-tests
      if: matrix.params.os != 'macos-latest' || matrix.config != 'Release'
    - name: test InteropSTL
      run: ./SC.sh build run InteropSTL ${{ matrix.config }}
    - name: compile SCTest xcode
      run: ./SC.sh build compile SCTest ${{ matrix.config }} xcode
      if: matrix.params.os == 'macos-latest' && matrix.config == 'Release'
    - name: test SCTest xcode
      run: ./SC.sh build run SCTest ${{ matrix.config }} xcode -- --all-tests
      if: matrix.params.os == 'macos-latest' && matrix.config == 'Release'
    # - name: install gdb
    #   run: sudo apt install -y gdb
    # - name: test in gdb
    #   run: gdb --batch -ex "run" -ex "quit" --args _Build/_Outputs/linux-x86_64-make-gcc-Debug/SCTest
    # - name: test in lldb
    #   run: lldb -o "run" -o "quit" -- _Build/_Outputs/macOS-x86_64-make-clang-Debug/SCTest
